name: Turbo Shadow Production

on:
  schedule:
    - cron: '50 4 * * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Режим (test або prod)'
        required: true
        default: 'test'
        type: choice
        options: [test, prod]

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
<<<<<<< HEAD
        uses: actions/checkout@v4 # Оновлено до v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Оновлено до v5
=======
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
>>>>>>> main
        with:
          python-version: '3.12' # Оновлено до Python 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Orchestrator
        env:
          GOOGLE_AI_KEY: ${{ secrets.GOOGLE_AI_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHAT_ID_TEST: ${{ secrets.TELEGRAM_CHAT_ID_TEST }}
          APP_MODE: ${{ github.event.inputs.mode || 'prod' }}
        run: python main.py

      - name: Commit & Push History
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Shadow-Bot-Automator"
          git add used_cars.json
          git commit -m "Automated update" || echo "No changes"
          git push
